language: php

php:
    - 5.6
    - 7.0
    - 7.1

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction

script: phpunit --configuration phpunit.xml --coverage-text

matrix:
    fast_finish: true

notifications:
    on_success: always
    on_failure: always
